# freshshell
source ~/.fresh/build/shell.sh

# antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen-bundles <<EOBUNDLES
bundler
git
heroku
zsh-users/zsh-syntax-highlighting
EOBUNDLES
antigen-theme robbyrussell
antigen-apply

# paths
export PATH=/home/oddmunds/.gem/ruby/2.0.0/bin:$PATH
export PATH=$PATH:/home/oddmunds/lib/play
export PATH=$PATH:/usr/bin/site_perl/

# VNVNVNNVVM
[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM

# exports
export EDITOR=vim

# aliases
alias pry='bundle exec pry || pry' # use bundle exec if available
alias l='ls --almost-all -l --reverse -t'
