# freshshell
source ~/.fresh/build/shell.sh

# antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen-bundles <<EOBUNDLES
bundler
git
heroku
zsh-users/zsh-syntax-highlighting
EOBUNDLES
antigen-theme robbyrussell
antigen-apply

# dirstack

DIRSTACKFILE="$HOME/.cache/zsh/dirs"
if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
  dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
  [[ -d $dirstack[1] ]] && cd $dirstack[1]
fi
chpwd() {
    print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
  }
DIRSTACKSIZE=20

setopt autopushd pushdsilent pushdtohome

setopt pushdignoredups
setopt pushdminus

# paths
export PATH=/home/oddmunds/.gem/ruby/2.1.0/bin:$PATH
export PATH=$PATH:/home/oddmunds/lib/play
export PATH=$PATH:/usr/bin/site_perl/
export PATH=$PATH:/usr/bin/vendor_perl/
export PATH=$PATH:/home/oddmunds/bin/

## amedia tools
export PATH=$PATH:/home/oddmunds/bin/api-tools/ci
export PATH=$PATH:/home/oddmunds/bin/api-tools/dev
export PATH=$PATH:/home/oddmunds/bin/api-tools/metrics/load
export PATH=$PATH:/home/oddmunds/bin/api-tools/metrics/yslow
export PATH=$PATH:/home/oddmunds/bin/api-tools/smoketests
export PATH=$PATH:/home/oddmunds/bin/api-tools/komparator


# VNVNVNNVVM
[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM

# exports
export EDITOR=vim
export PACMAN=pacmatic

export V3_CONFIG_HOME=/etc/api

export M2_HOME=/opt/maven

# aliases
alias l='ls --almost-all -l --reverse -t'
alias pry='bundle exec pry || pry' # use bundle exec if available
alias qtip='gradle clean ear'
alias v='vim'
alias h='http -b --follow'
alias gff='git pull --ff-only'

# PROMPT HACK
export PS1='%{$fg_bold[red]%}⮁ %{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'
